# Site
repository: sproogen/resume-theme

# Personal info
name: 양경빈 Yang KyungBin
title: Junior iOS Developer
email: crea9813@gmail.com
website: https://crea9813.github.io

# Social links
github_username:  crea9813
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: yanggang02
linkedin_username: kyungbin-y-00260713a
# pinterest_username: jekyll
# googleplus_username: +jekyll

# About Section
about_title: 간단 소개
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  현업에 이제 막 뛰어들었지만, 소프트웨어 전공 고등학교 과정 중 꾸준히 프로젝트를 통해 실무경험을 쌓아왔으며, 사람들에게 기억될만한 앱을 만드는 것이 목표인 개발자입니다. 창업을 통해 앱 개발자의 역할을 맡았던 경험이 있습니다.
  
  비즈니스 성장에 기여하는 일을 좋아합니다. 이를 위해 일정에 맞추어 개발하고 배포하는 역량과 소통하는 역량을 쌓고자 노력해왔습니다. 또한, <mark>혼자가 아닌 함께</mark> 만들어나간다고 생각하기에 다양한 직무에 대해서도 이해하고 적극적으로 소통하기 위해 노력해왔습니다.
  
  최근엔 <mark>최적화된 코드</mark>에 대해 고민하고 있습니다.
  제작한 프로젝트에 새로운 디자인 패턴과 코드 최적화를 진행하고 여전히 업데이트를 진행 중입니다.

# Projects Section
projects_title: 프로젝트

# Experience Section
experience_title: 경험

# Education Section
educaton_title: 교육

# More Section
more_title: Skill
more_content: | # this will include new lines to allow paragraphs
  - iOS 앱 개발 : Swift, Objective-C, Alamofire, Realm, RxSwift, Snapkit
  - Android 앱 개발 : Java, Kotlin, Retrofit2
  - Database : SQLlite

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
